import React from 'react'
import './Vijesti.css';
import NavBar from '../components/NavBar';


const source = [
  {titleN: "NASLOV NOVOSTI PRIMJER", textN: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras laoreet ultricies tellus quis ultrices. Cras pharetra dapibus leo mattis porta. Mauris at vehicula mi. Sed sed vehicula leo. Phasellus ac sapien id sapien blandit maximus et et magna. Integer elementum pretium auctor. In at aliquet erat, id aliquam sapien. Nulla imperdiet condimentum erat sed molestie. Suspendisse vel imperdiet ipsum. Integer ultricies ligula in massa vehicula, sed lobortis leo finibus. Cras dui mi, imperdiet ac viverra a, consectetur vel metus. Aliquam condimentum, sapien ac venenatis consectetur, velit lacus convallis felis, at mattis nisi tortor sed felis. Nulla sit amet tincidunt lacus. Aliquam faucibus malesuada mauris ut rhoncus. Donec eget ultrices sapien. Suspendisse potenti."},
  {titleN: "NASLOV NOVOSTI PRIMJER", textN: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras laoreet ultricies tellus quis ultrices. Cras pharetra dapibus leo mattis porta. Mauris at vehicula mi. Sed sed vehicula leo. Phasellus ac sapien id sapien blandit maximus et et magna. Integer elementum pretium auctor. In at aliquet erat, id aliquam sapien. Nulla imperdiet condimentum erat sed molestie. Suspendisse vel imperdiet ipsum. Integer ultricies ligula in massa vehicula, sed lobortis leo finibus. Cras dui mi, imperdiet ac viverra a, consectetur vel metus. Aliquam condimentum, sapien ac venenatis consectetur, velit lacus convallis felis, at mattis nisi tortor sed felis. Nulla sit amet tincidunt lacus. Aliquam faucibus malesuada mauris ut rhoncus. Donec eget ultrices sapien. Suspendisse potenti."},
  {titleN: "NASLOV NOVOSTI PRIMJER", textN: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras laoreet ultricies tellus quis ultrices. Cras pharetra dapibus leo mattis porta. Mauris at vehicula mi. Sed sed vehicula leo. Phasellus ac sapien id sapien blandit maximus et et magna. Integer elementum pretium auctor. In at aliquet erat, id aliquam sapien. Nulla imperdiet condimentum erat sed molestie. Suspendisse vel imperdiet ipsum. Integer ultricies ligula in massa vehicula, sed lobortis leo finibus. Cras dui mi, imperdiet ac viverra a, consectetur vel metus. Aliquam condimentum, sapien ac venenatis consectetur, velit lacus convallis felis, at mattis nisi tortor sed felis. Nulla sit amet tincidunt lacus. Aliquam faucibus malesuada mauris ut rhoncus. Donec eget ultrices sapien. Suspendisse potenti."},
  {titleN: "NASLOV NOVOSTI PRIMJER", textN: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras laoreet ultricies tellus quis ultrices. Cras pharetra dapibus leo mattis porta. Mauris at vehicula mi. Sed sed vehicula leo. Phasellus ac sapien id sapien blandit maximus et et magna. Integer elementum pretium auctor. In at aliquet erat, id aliquam sapien. Nulla imperdiet condimentum erat sed molestie. Suspendisse vel imperdiet ipsum. Integer ultricies ligula in massa vehicula, sed lobortis leo finibus. Cras dui mi, imperdiet ac viverra a, consectetur vel metus. Aliquam condimentum, sapien ac venenatis consectetur, velit lacus convallis felis, at mattis nisi tortor sed felis. Nulla sit amet tincidunt lacus. Aliquam faucibus malesuada mauris ut rhoncus. Donec eget ultrices sapien. Suspendisse potenti."},
  {titleN: "NASLOV NOVOSTI PRIMJER", textN: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras laoreet ultricies tellus quis ultrices. Cras pharetra dapibus leo mattis porta. Mauris at vehicula mi. Sed sed vehicula leo. Phasellus ac sapien id sapien blandit maximus et et magna. Integer elementum pretium auctor. In at aliquet erat, id aliquam sapien. Nulla imperdiet condimentum erat sed molestie. Suspendisse vel imperdiet ipsum. Integer ultricies ligula in massa vehicula, sed lobortis leo finibus. Cras dui mi, imperdiet ac viverra a, consectetur vel metus. Aliquam condimentum, sapien ac venenatis consectetur, velit lacus convallis felis, at mattis nisi tortor sed felis. Nulla sit amet tincidunt lacus. Aliquam faucibus malesuada mauris ut rhoncus. Donec eget ultrices sapien. Suspendisse potenti."},
  {titleN: "NASLOV NOVOSTI PRIMJER", textN: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras laoreet ultricies tellus quis ultrices. Cras pharetra dapibus leo mattis porta. Mauris at vehicula mi. Sed sed vehicula leo. Phasellus ac sapien id sapien blandit maximus et et magna. Integer elementum pretium auctor. In at aliquet erat, id aliquam sapien. Nulla imperdiet condimentum erat sed molestie. Suspendisse vel imperdiet ipsum. Integer ultricies ligula in massa vehicula, sed lobortis leo finibus. Cras dui mi, imperdiet ac viverra a, consectetur vel metus. Aliquam condimentum, sapien ac venenatis consectetur, velit lacus convallis felis, at mattis nisi tortor sed felis. Nulla sit amet tincidunt lacus. Aliquam faucibus malesuada mauris ut rhoncus. Donec eget ultrices sapien. Suspendisse potenti."},
  {titleN: "NASLOV NOVOSTI PRIMJER", textN: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras laoreet ultricies tellus quis ultrices. Cras pharetra dapibus leo mattis porta. Mauris at vehicula mi. Sed sed vehicula leo. Phasellus ac sapien id sapien blandit maximus et et magna. Integer elementum pretium auctor. In at aliquet erat, id aliquam sapien. Nulla imperdiet condimentum erat sed molestie. Suspendisse vel imperdiet ipsum. Integer ultricies ligula in massa vehicula, sed lobortis leo finibus. Cras dui mi, imperdiet ac viverra a, consectetur vel metus. Aliquam condimentum, sapien ac venenatis consectetur, velit lacus convallis felis, at mattis nisi tortor sed felis. Nulla sit amet tincidunt lacus. Aliquam faucibus malesuada mauris ut rhoncus. Donec eget ultrices sapien. Suspendisse potenti."},
  {titleN: "NASLOV NOVOSTI PRIMJER", textN: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras laoreet ultricies tellus quis ultrices. Cras pharetra dapibus leo mattis porta. Mauris at vehicula mi. Sed sed vehicula leo. Phasellus ac sapien id sapien blandit maximus et et magna. Integer elementum pretium auctor. In at aliquet erat, id aliquam sapien. Nulla imperdiet condimentum erat sed molestie. Suspendisse vel imperdiet ipsum. Integer ultricies ligula in massa vehicula, sed lobortis leo finibus. Cras dui mi, imperdiet ac viverra a, consectetur vel metus. Aliquam condimentum, sapien ac venenatis consectetur, velit lacus convallis felis, at mattis nisi tortor sed felis. Nulla sit amet tincidunt lacus. Aliquam faucibus malesuada mauris ut rhoncus. Donec eget ultrices sapien. Suspendisse potenti."},
];

function Vijesti() {
  return (
    <><NavBar></NavBar>
      {source.map((val, key) => {
            return (
              <div className='novost'>
                <div className='naslov'><text>{val.titleN}</text></div>
                <div className='textNovosti'><text>{val.textN}</text></div>
              </div>
            )
          })}
    </>
  )
}

export default Vijesti
